name: 'ecommerce_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_lakehouse:
    silver:
      +materialized: external
    gold:
      +materialized: external

vars:
  bronze_bucket: "dev-lakehouse-bronze"
  silver_bucket: "dev-lakehouse-silver"
  gold_bucket: "dev-lakehouse-gold"