airflow:
  id: "dbt_run_silver"
  dependencies:
    - dag_id: "ecommerce_db_fetch"
      task_id: "ingest_users_to_bronze"
    - dag_id: "ecommerce_db_fetch"
      task_id: "ingest_orders_to_bronze"

dbt:
  model: silver # Staging & Deduplicatio